/**
 * Socket.IO Service - Real-time communication with AlephScriptClient
 * 
 * Connects to ws-server (Socket.IO) as AAIABackendBot
 * Joins AAIA_ROOM and listens for events from MCPAAIAServer
 * Re-broadcasts events to connected REST clients via SSE
 * 
 * AsyncAPI Events:
 * - fia_step: FIA executed a step
 * - percepto: Percepto received by FIA
 * - eferencia: Eferencia generated by FIA
 * - mundo_state: World state changed
 * - session_created: New session started
 * - session_destroyed: Session terminated
 */

import { io, Socket } from 'socket.io-client';
import { EventEmitter } from 'events';
import { config } from '../config';
import { logger } from '../utils/logger';

// ============================================
// Event Types (aligned with AsyncAPI)
// ============================================

export interface FIAStepEvent {
  sessionId: string;
  fiaIndex: number;
  runState: string;
  timestamp: string;
}

export interface PerceptoEvent {
  sessionId: string;
  percepto: {
    name: string;
    value: unknown;
    source: string;
  };
  timestamp: string;
}

export interface EferenciaEvent {
  sessionId: string;
  fiaIndex: number;
  eferencia: {
    accion: string;
    destino: string;
    datos: unknown;
  };
  timestamp: string;
}

export interface MundoStateEvent {
  sessionId: string;
  state: Record<string, unknown>;
  timestamp: string;
}

export interface SessionEvent {
  sessionId: string;
  appId?: string;
  timestamp: string;
}

// Union type for all events
export type AAIAEvent = 
  | { type: 'fia_step'; data: FIAStepEvent }
  | { type: 'percepto'; data: PerceptoEvent }
  | { type: 'eferencia'; data: EferenciaEvent }
  | { type: 'mundo_state'; data: MundoStateEvent }
  | { type: 'session_created'; data: SessionEvent }
  | { type: 'session_destroyed'; data: SessionEvent };

// ============================================
// SSE Client Management
// ============================================

export interface SSEClient {
  id: string;
  sessionId: string | null; // null = all sessions
  send: (event: string, data: unknown) => void;
  close: () => void;
}

// ============================================
// Socket.IO Service Class
// ============================================

class SocketIOService extends EventEmitter {
  private socket: Socket | null = null;
  private connected: boolean = false;
  private reconnectAttempts: number = 0;
  private readonly MAX_RECONNECT_ATTEMPTS = 10;
  private sseClients: Map<string, SSEClient> = new Map();
  private eventBuffer: AAIAEvent[] = [];
  private readonly BUFFER_SIZE = 100;

  constructor() {
    super();
    this.setMaxListeners(50); // Allow many SSE clients
  }

  // ============================================
  // Connection Management
  // ============================================

  /**
   * Connect to Socket.IO server
   */
  async connect(): Promise<void> {
    if (this.socket?.connected) {
      logger.debug('Socket.IO already connected');
      return;
    }

    return new Promise((resolve, reject) => {
      try {
        logger.info(`Connecting to Socket.IO at ${config.socketio.url}`);

        this.socket = io(config.socketio.url, {
          transports: ['websocket', 'polling'],
          autoConnect: true,
          reconnection: true,
          reconnectionAttempts: this.MAX_RECONNECT_ATTEMPTS,
          reconnectionDelay: 1000,
          reconnectionDelayMax: 10000,
          timeout: 10000,
          auth: {
            botId: 'AAIABackendBot',
            botType: 'gateway',
          },
        });

        this.setupEventHandlers();

        // Wait for connection
        const timeout = setTimeout(() => {
          reject(new Error('Socket.IO connection timeout'));
        }, 15000);

        this.socket.on('connect', () => {
          clearTimeout(timeout);
          this.connected = true;
          this.reconnectAttempts = 0;
          this.joinRoom();
          resolve();
        });

        this.socket.on('connect_error', (error) => {
          clearTimeout(timeout);
          logger.error('Socket.IO connection error:', error.message);
          reject(error);
        });
      } catch (error) {
        reject(error);
      }
    });
  }

  /**
   * Disconnect from Socket.IO server
   */
  disconnect(): void {
    if (this.socket) {
      this.socket.disconnect();
      this.socket = null;
      this.connected = false;
      logger.info('Socket.IO disconnected');
    }
  }

  /**
   * Join AAIA_ROOM
   */
  private joinRoom(): void {
    if (!this.socket) return;

    const room = config.socketio.room;
    logger.info(`Joining room: ${room}`);

    this.socket.emit('join_room', { room }, (ack: { success: boolean; error?: string }) => {
      if (ack?.success) {
        logger.info(`Joined room: ${room}`);
      } else {
        logger.error(`Failed to join room: ${ack?.error}`);
      }
    });
  }

  /**
   * Setup event handlers for AAIA events
   */
  private setupEventHandlers(): void {
    if (!this.socket) return;

    // Connection events
    this.socket.on('connect', () => {
      logger.info('Socket.IO connected');
      this.connected = true;
    });

    this.socket.on('disconnect', (reason) => {
      logger.warn(`Socket.IO disconnected: ${reason}`);
      this.connected = false;
    });

    this.socket.on('reconnect', (attempt) => {
      logger.info(`Socket.IO reconnected after ${attempt} attempts`);
      this.connected = true;
      this.joinRoom();
    });

    this.socket.on('reconnect_failed', () => {
      logger.error('Socket.IO reconnection failed');
      this.connected = false;
    });

    // AAIA Events
    this.socket.on('fia_step', (data: FIAStepEvent) => {
      this.handleEvent({ type: 'fia_step', data });
    });

    this.socket.on('percepto', (data: PerceptoEvent) => {
      this.handleEvent({ type: 'percepto', data });
    });

    this.socket.on('eferencia', (data: EferenciaEvent) => {
      this.handleEvent({ type: 'eferencia', data });
    });

    this.socket.on('mundo_state', (data: MundoStateEvent) => {
      this.handleEvent({ type: 'mundo_state', data });
    });

    this.socket.on('session_created', (data: SessionEvent) => {
      this.handleEvent({ type: 'session_created', data });
    });

    this.socket.on('session_destroyed', (data: SessionEvent) => {
      this.handleEvent({ type: 'session_destroyed', data });
    });
  }

  /**
   * Handle incoming event - buffer and broadcast
   */
  private handleEvent(event: AAIAEvent): void {
    logger.debug(`AAIA Event: ${event.type}`, event.data);

    // Add to buffer (for new SSE clients)
    this.eventBuffer.push(event);
    if (this.eventBuffer.length > this.BUFFER_SIZE) {
      this.eventBuffer.shift();
    }

    // Emit to internal listeners
    this.emit('aaia_event', event);
    this.emit(event.type, event.data);

    // Broadcast to SSE clients
    this.broadcastToSSEClients(event);
  }

  // ============================================
  // SSE Client Management
  // ============================================

  /**
   * Register an SSE client
   */
  registerSSEClient(client: SSEClient): void {
    this.sseClients.set(client.id, client);
    logger.debug(`SSE client registered: ${client.id} (session: ${client.sessionId || 'all'})`);

    // Send buffered events
    this.eventBuffer.forEach(event => {
      if (this.shouldSendToClient(client, event)) {
        client.send(event.type, event.data);
      }
    });
  }

  /**
   * Unregister an SSE client
   */
  unregisterSSEClient(clientId: string): void {
    const client = this.sseClients.get(clientId);
    if (client) {
      client.close();
      this.sseClients.delete(clientId);
      logger.debug(`SSE client unregistered: ${clientId}`);
    }
  }

  /**
   * Check if event should be sent to client
   */
  private shouldSendToClient(client: SSEClient, event: AAIAEvent): boolean {
    // If client subscribes to all sessions
    if (!client.sessionId) return true;

    // Check if event is for client's session
    const sessionId = 'sessionId' in event.data ? event.data.sessionId : null;
    return sessionId === client.sessionId;
  }

  /**
   * Broadcast event to all SSE clients
   */
  private broadcastToSSEClients(event: AAIAEvent): void {
    this.sseClients.forEach(client => {
      if (this.shouldSendToClient(client, event)) {
        try {
          client.send(event.type, event.data);
        } catch (error) {
          logger.warn(`Failed to send event to SSE client ${client.id}:`, error);
          this.unregisterSSEClient(client.id);
        }
      }
    });
  }

  // ============================================
  // Emit Events to Socket.IO (for backend-initiated events)
  // ============================================

  /**
   * Emit event to AAIA_ROOM
   */
  emitToRoom(eventName: string, data: unknown): void {
    if (!this.socket?.connected) {
      logger.warn('Cannot emit: Socket.IO not connected');
      return;
    }

    const room = config.socketio.room;
    this.socket.emit('room_message', {
      room,
      event: eventName,
      data,
    });
  }

  // ============================================
  // Status
  // ============================================

  isConnected(): boolean {
    return this.connected && this.socket?.connected === true;
  }

  getStatus(): {
    connected: boolean;
    room: string;
    sseClients: number;
    bufferedEvents: number;
  } {
    return {
      connected: this.isConnected(),
      room: config.socketio.room,
      sseClients: this.sseClients.size,
      bufferedEvents: this.eventBuffer.length,
    };
  }
}

// Singleton instance
export const socketIOService = new SocketIOService();
